-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."files" add column "sharedDepartment" boolean
--  null default 'False';
